### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by SaYiiTo21** [North-West-Wind/CurseForge-CLI#18]
Hi, so when i do java -jar curseforge-cli.jar , I receive this exception : 

CurseForge CLI v1.3.7
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.json.simple.JSONObject.get(Object)" because "details" is null
	at ml.northwestwind.Utils.readUpdate(Utils.java:255)
	at ml.northwestwind.Main.main(Main.java:16)

**Comment by HootmanXD** [comment]
I am having the same issue on the latest 1.4.0 Version.

Been trying to find a way to correct this, no luck so far.

Of note:
I am on a new install of Fedora37 (minecraft itself runs fine)
Before I had updated to Fedora37, I was running the prior version without issue.
Also the cf.json file still generates.

**Comment by North-West-Wind** [comment]
I put the wrong "latest" version in the update file. Just changed it so this should be fixed now.
