### ISSUE TITLE
java.io.IOException: Server returned HTTP response code: 503 for URL: https://northwestwind.ml/api/curseforge/mods/3785858

### ISSUE THREAD

**Issue by Lyceris-chan** [North-West-Wind/CurseForge-CLI#8]
Heyo first of all thanks for your work

I launched my google cloud console instance and used wget to download the jar and the zip and both gave me the same results being:

Command: ./curseforge modpack install 3785858
(this is the specific version of a modpack we use ([all the mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/3785858)

result: java.io.IOException: Server returned HTTP response code: 503 for URL: https://northwestwind.ml/api/curseforge/mods/3785858
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at java.base/java.net.URL.openStream(URL.java:1165)
        at ml.northwestwind.Utils.readJsonFromUrl(Utils.java:163)
        at ml.northwestwind.Utils.readJsonFromUrl(Utils.java:158)
        at ml.northwestwind.Modpack.lambda$install$1(Modpack.java:55)
        at ml.northwestwind.Utils.runRetry(Utils.java:266)
        at ml.northwestwind.Modpack.install(Modpack.java:55)
        at ml.northwestwind.Modpack.run(Modpack.java:32)
        at ml.northwestwind.Main.main(Main.java:28)

**Comment by North-West-Wind** [comment]
Unfortunately, there is currently no support for installing a specific version of mods/modpacks. This issue will be left as a future feature to implement.

What you can do now is to directly download the modpack zip file, and run `./curseforge profile import <path>`. The modpack will be imported as a profile.

**Comment by North-West-Wind** [comment]
Hi there! I just updated the program and now you can install with
```bash
./curseforge modpack install 426926_3785858
```
